## 作業 example.csv 漲跌點數大於9.34的幫我輸出 他的漲跌點數

In [2]:
import csv
f = open("example.csv","r",encoding="utf-8")
for row in csv.DictReader(f):
    if float(row["漲跌點數"]) > 9.34:
        print(row["漲跌點數"])
f.close()        

101.17
29.59
47.89
85.83
117.46
12.61
173.72
109.67


In [3]:
import csv
with open("example.csv","r",encoding="utf-8") as f:
    for row in csv.DictReader(f):
        if float(row["漲跌點數"]) > 9.34:
            print(row["漲跌點數"])

101.17
29.59
47.89
85.83
117.46
12.61
173.72
109.67


In [ ]:
import csv
with open("example.csv","r",encoding="rtf-8") as f:
    for row in csv.DictReader(f):
        if float(row["漲跌點數"]) > 9.34:
            print(row["漲跌點數"])

## Json

In [10]:
import json
json1 = {'python':"課程",'gjun':100,"python-class":True,"Line":None}
print(json1)
jsonStr = json.dumps(json1,ensure_ascii=False)
print(type(jsonStr))
print(jsonStr)

{'python': '課程', 'gjun': 100, 'python-class': True, 'Line': None}
<class 'str'>
{"python": "課程", "gjun": 100, "python-class": true, "Line": null}


In [12]:
import json
json1 = {'python':"課程",'gjun':100,"python-class":True,"Line":None}
with open("data0.json","w",encoding="utf-8") as f:
    json.dump(json1,f,ensure_ascii=False)

In [17]:
import json
data = { }
data['people'] = [ ]
data['people'].append({
    'name': 'Scott',
    'website': 'stackabuse.com',
    'from': 'Nebraska'
})
data['people'].append({
    'name': 'Larry',
    'website': 'google.com',
    'from': 'Michigan'
})

with open("data.json","w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False,indent=1)

## Json轉換為Python物件

In [18]:
import json
json1 = '{"python":"good","gjun":100,"python-class":true,"ICQ":null}'
json2 = json.loads(json1)
print(json2)
print(type(json2))
print(json2["gjun"])

{'python': 'good', 'gjun': 100, 'python-class': True, 'ICQ': None}
<class 'dict'>
100


In [ ]:
import json
with open("data.json","r",encoding="utf-8") as f:
    data = json.load(f)
    print(data)
    print(data["people"][0]["website"])


{'people': [{'name': 'Scott', 'website': 'stackabuse.com', 'from': 'Nebraska'}, {'name': 'Larry', 'website': 'google.com', 'from': 'Michigan'}]}
<class 'str'>
stackabuse.com


## Numpy

+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [ ]:
import numpy as np
i = [[1,2,3],
     [4,5,6]]
#2x3
a = np.array(i)
print(a)
print(a.ndim)#維度
print(a.shape)#形狀
myShape = a.shape
print(type(myShape))
print(myShape[0])
print(myShape[1])
#軸
print(a.size)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
<class 'tuple'>
2
3
6
int64


In [44]:
import numpy as np
i = [[1,2,3],
     [2.5,3.6,7.8]]
a = np.array(i)
print(a)
print(a.dtype)

[[1.  2.  3. ]
 [2.5 3.6 7.8]]
float64


In [46]:
import numpy as np
i = [[1,2,3],
     [2.5,3.6,7.8]]
a = np.array(i)
print(a)
print(a.dtype)

[[1.  2.  3. ]
 [2.5 3.6 7.8]]
float64


In [2]:
import numpy as np
i = [[2.5,3.6,18.2],
     ["A","B","C"]]
a = np.array(i)
print(a)
print(a.dtype)


[['2.5' '3.6' '18.2']
 ['A' 'B' 'C']]
<U32


In [6]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
c = a * b
print(c)
c = a ** 2
print(c)

[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
[ 0  7 16 27]
[36 49 64 81]


In [13]:
import numpy as np
f = np.array([5,-1,3,9,0])
print(f)
fArray = f <= 3
print(fArray)
newArray = f[fArray]
print(newArray)
newArray2 = f[f <= 3]
print(newArray2)

[ 5 -1  3  9  0]
[False  True  True False  True]
[-1  3  0]
[-1  3  0]


In [22]:
import numpy as np
x = np.arange(8)
print(x)
x2 = np.arange(1.5,9,0.5)
print("[",end="")
for v in x2:
    print(v,end=" ")
print("]",end="")
print()  
print(x2)

[0 1 2 3 4 5 6 7]
[1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0 8.5 ]
[1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


In [23]:
import numpy as np
lin = np.linspace(3,5,9)#5-3 / 9- 1
print(lin)

[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [25]:
import numpy as np
a1 = np.arange(8)
print(a1)
newA2 = a1.reshape((2,4))
print(newA2)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [32]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[0])
print(a[1][1])
print(a[2][1])
print(a[1,1])
print(a[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
5
8
5
6


In [ ]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[1,1:])
## 作業
#8 9

# 5 6 
# 8 9

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]
