In [11]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[1,1:])
## 作業
#8 9
print(a[2,1:])
# 5 6 
# 8 9
print(a[1:,1:])
#修改
a[1,2] =  75
print(a)
a[:,0] = [100,101,102]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]
[8 9]
[[5 6]
 [8 9]]
[[ 1  2  3]
 [ 4  5 75]
 [ 7  8  9]]
[[100   2   3]
 [101   5  75]
 [102   8   9]]


In [15]:
import numpy as np
a  = np.arange(0,36).reshape((6,6))
print(a)
print("="*50)
print(a[0,3:5])
print("="*50)
print(a[4:,4:])
print("="*50)
print(a[:3,:3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[3 4]
[[28 29]
 [34 35]]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [ ]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print(a)
print()
b = a.reshape((1,6))#reshape 資料共用只改變擺放的位置 省記憶體空間
print(b)
print(b.shape)

a[0,1] = 100
print("a:",a)
print("b:",b)

(2, 3)
[[1 2 3]
 [4 5 6]]

[[1 2 3 4 5 6]]
(1, 6)
a: [[  1 100   3]
 [  4   5   6]]
b: [[  1 100   3   4   5   6]]


In [21]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print(a.shape)
print()
b = np.resize(a,(3,2))
print(b)
print(b.shape)
a[0,1] = 100
print()
print("a:",a)
print("a:",a.shape)
print()
print("b:",b)
print("b:",b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

a: [[  1 100   3]
 [  4   5   6]]
a: (2, 3)

b: [[1 2]
 [3 4]
 [5 6]]
b: (3, 2)


In [24]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = a.reshape((3,2))
print(b)
b = a.reshape((7,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


ValueError: cannot reshape array of size 6 into shape (7,2)

In [26]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.resize(a,(10,10))
print(b)

[[1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4]]


In [29]:
import numpy as np
newArray = np.arange(10).reshape(2,5)
print(newArray)
print(newArray.shape)
tArray =  newArray.T
print(tArray)
print(tArray.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
(5, 2)


In [31]:
import numpy as np
x = np.loadtxt("data1.csv",delimiter=",")
print(x)
print(x*2)

[[0.2 0.1]
 [0.4 0.3]
 [0.1 0.6]
 [0.1 0.3]
 [0.5 0.3]]
[[0.4 0.2]
 [0.8 0.6]
 [0.2 1.2]
 [0.2 0.6]
 [1.  0.6]]


In [37]:
import numpy as np
x,y = np.loadtxt("data1.csv",unpack=True,delimiter=",")
print(x)
print(y)

[0.2 0.4 0.1 0.1 0.5]
[0.1 0.3 0.6 0.3 0.3]


## 總和最大與最小
+ np.sum( ) 代表某一個陣列內容的總和，也可以指定這個陣列的哪一軸 (axis) 內容總和。
+ np.min( ) 代表某一個陣列內容的最小值，也可以指定這個陣列的哪一軸 (axis) 內容的最小值。
+ np.max( ) 代表某一個陣列內容的最大值，也可以指定這個陣列的哪一軸 (axis) 內容的最大值。
+ amin 與 min 是相同功能的方法。
+ amax 與 max 是相同功能的方法。

In [44]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
s = a.shape
print(s)
print(s[0])#軸0
print(s[1])#軸1
print("="*50)
b = np.sum(a)#每個元素相加
print(b)
print("="*50)
b = np.sum(a,axis=0)
print(b)
print("="*50)
b = np.sum(a,axis=1)
print(b)
print("="*50)

[[ 0 30 45]
 [60 75 90]]
(2, 3)
2
3
300
[ 60 105 135]
[ 75 225]


In [49]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
print("======================")
b = np.max(a)
bi = np.argmax(a)
print(b)
print(bi)
print("======================")
b = np.max(a,axis=0)
print(b)
print("======================")
b = np.max(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
90
5
[60 75 90]
[45 90]


In [52]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
print()
b = np.mean(a)#平均值
print(b)
print()
b = np.mean(a,axis=0)
print(b)
print()
b = np.mean(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]

50.0

[30.  52.5 67.5]

[25. 75.]


In [55]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
print()
b = np.median(a)
print(b)
print()
b = np.median(a,axis=0)
print(b)
print()
b = np.median(a,axis=1)
print(b)
print()

[[ 0 30 45]
 [60 75 90]]

52.5

[30.  52.5 67.5]

[30. 75.]



## 變異數與標準差
+ 變異數代表所有資料到平均數的距離之平方。
+ 標準差代表變異數開平方根，也就是可依此表示資料的分散程度。
+ var( ) 代表由陣列取得變異數的方法。
+ std( ) 代表由陣列取得標準差的方法。

+ 定義：

+ 變異數代表((每一個資料-平均值)平方後的加總結果)/總個數。

+ 標準差是變異數的開根號結果。



In [57]:
import numpy as np
a = np.array([1,2,3,4])
b = np.var(a)
print(b)
b = np.std(a)
print(round(b,2))

1.25
1.12


In [59]:
import numpy as np
import math
a = np.array([1,2,3,4])
mean = a.mean()
var = ((a-mean) ** 2).mean()
print(var)
std = math.sqrt(var)
print(std)

1.25
1.118033988749895


In [ ]:
import numpy as np
girl=np.array([8,10,15,20,27,29,29,30,30,162])
boy=np.array([34,34,35,35,36,36,36,37,38,39])
print("girl:",girl)
print("boy:",boy)
girl_mena = np.mean(girl)
boy_mean = np.mean(boy)
print("girl_mena:",girl_mena)
print("boy_mean:",boy_mean)
girl_std = girl.std()
boy_std = boy.std()
girl_var = girl.var()
boy_var = boy.var()
print("girl_std:",girl_std)
print("boy_std:",boy_std)

print("girl_var:",girl_var)
print("boy_var:",boy_var)

print("girl:",np.median(girl))
print("boy:",np.mean(boy))

girl: [  8  10  15  20  27  29  29  30  30 162]
boy: [34 34 35 35 36 36 36 37 38 39]
girl_mena: 36.0
boy_mean: 36.0
girl_std: 42.75979419969184
boy_std: 1.5491933384829668
girl_var: 1828.4
boy_var: 2.4
girl: 28.0
boy: 36.0


## 作業
## 請計算出 106 與 107 年每個月 0 到 9歲國小(含)之前的人數總計


106 1國小(含)之前的人數573

106 2國小(含)之前的人數569

106 3國小(含)之前的人數572

106 4國小(含)之前的人數560

106 5國小(含)之前的人數570

106 6國小(含)之前的人數577


## 累加

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], 
              [13, 6, 9],
              [12, 24, 36]])
print(a)
print(np.cumsum(a))
print(np.cumsum(a,axis=0))
print(np.cumsum(a,axis=1))

[[ 1  2  3]
 [13  6  9]
 [12 24 36]]
[  1   3   6  19  25  34  46  70 106]
[[ 1  2  3]
 [14  8 12]
 [26 32 48]]
